Add field `can_manage_video_chats` to ChatMemberOwner
aiogram/aiogram pull request #1003
Opened 2022-09-17 21:40 UTC by andrew000

# Description

Type here...

Add field `can_manage_video_chats` to ChatMemberOwner

- New feature (non-breaking change that adds functionality)

# How has this been tested?

No tests, just add field

## Test Configuration
- Operating system: e.g. Ubuntu 20.04.2 LTS
-Python version: e.g. 3.10.1

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have added tests that prove my fix is effective or that my feature works as expected
- [x] New and existing unit tests pass locally with my changes
- [x] My changes generate no new warnings or errors
- [x] My changes are compatible with minimum requirements of the project
- [ ] I have made corresponding changes to the documentation

2022-09-17 21:45 UTC, evgfilim1 commented
I guess it must be renamed with deprecation

![image](https://user-images.githubusercontent.com/17182159/190877334-31a12b5d-9c62-4aae-b6d6-ed032af9abe6.png)
https://core.telegram.org/bots/api#april-16-2022

2022-09-17 23:12 UTC, Olegt0rr requested changes

2022-09-17 23:12 UTC, Olegt0rr commented on aiogram/types/chat_member.py
> +    can_manage_video_chats: base.Boolean = fields.ConstField(True)
Don't forget to check other usage of previous name

2022-09-18 16:57 UTC, andrew000 commented
TESTS:
![image](https://user-images.githubusercontent.com/11490628/190919124-521b17b2-495e-4c37-add9-2d538fe8dac0.png)

2022-09-20 13:02 UTC, Olegt0rr commented
> TESTS: ![image](https://user-images.githubusercontent.com/11490628/190919124-521b17b2-495e-4c37-add9-2d538fe8dac0.png)

this should be issue for tests

2022-09-20 13:07 UTC, andrew000 commented
> > TESTS: ![image](https://user-images.githubusercontent.com/11490628/190919124-521b17b2-495e-4c37-add9-2d538fe8dac0.png)
> 
> this should be issue for tests

Since all the tests are passed, is it possible to merge the pr?

2022-09-20 13:07 UTC, andrew000 commented
> > TESTS: ![image](https://user-images.githubusercontent.com/11490628/190919124-521b17b2-495e-4c37-add9-2d538fe8dac0.png)
> 
> this should be issue for tests

Since all the tests are passed, is it possible to merge PR?

2022-09-23 23:48 UTC, Olegt0rr approved these changes

2022-09-24 21:15 UTC, merged