Add missing `Message` methods
aiogram/aiogram pull request #1030
Opened 2022-10-18 06:55 UTC by Danipulok

# Add missing `Message` methods

Add following methods to `Message`:
```
Message.forward(...)
Message.edit_media(...)
Message.edit_live_location(...)
Message.stop_live_location(...)
Message.pin(...)
Message.unpin()
```
For each method add: 
- code
- test
- documentation

## Type of change
- New feature (non-breaking change that adds functionality)

# How has this been tested?
Add new tests in `tests/test_api/test_types/test_message.py`

## Test Configuration
Git hooks

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have added tests that prove my fix is effective or that my feature works as expected
- [x] New and existing unit tests pass locally with my changes
- [x] My changes generate no new warnings or errors
- [x] My changes are compatible with minimum requirements of the project
- [x] I have made corresponding changes to the documentation

2022-10-18 10:11 UTC, evgfilim1 approved these changes

2022-10-21 19:23 UTC, JrooTJunior requested changes

2022-10-21 19:23 UTC, JrooTJunior commented on CHANGES/1030.feature.rst
> +Add following methods to ``Message`` class:
```suggestion
Added following methods to ``Message`` class:
```

2022-10-21 19:57 UTC, Danipulok commented
@JrooTJunior done

2022-10-21 21:29 UTC, merged