add new method
aiogram/aiogram pull request #1049
Opened 2022-10-30 18:25 UTC by sheldygg

# Description

I'm tired of writing like this
```python
html.link(message.from_user.full_name, f'tg://user?id={message.from_user.id}')
```
so i did it pull request

## Type of change

- adding method to get to get mention of user

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have added tests that prove my fix is effective or that my feature works as expected
- [x] New and existing unit tests pass locally with my changes
- [x] My changes generate no new warnings or errors
- [x] My changes are compatible with minimum requirements of the project
- [ ] I have made corresponding changes to the documentation

2022-10-31 06:25 UTC, evgfilim1 requested changes
Please fix your code formatting by running `black` and `isort` from project directory.

2022-10-31 06:25 UTC, evgfilim1 commented on tests/test_api/test_types/test_user.py
> +        assert user.mention_html()
Don't edit tests, add new ones instead

2022-10-31 06:25 UTC, evgfilim1 commented on tests/test_api/test_types/test_user.py
> +        assert user.mention_html()
Don't assert string values unless you're checking that something is expected to be non-empty. In your case, you must check if `mention_html` returns exact string. Then try to add arguments and see if it works properly. And don't forget to test `mention_markdown`.

2022-10-31 06:35 UTC, sheldygg reviewed
fix

2022-10-31 22:49 UTC, JrooTJunior requested changes

2022-10-31 22:49 UTC, JrooTJunior commented on aiogram/types/user.py
> +        return f"tg://user?id={self.id}"
Is preffered to use `create_tg_link` function which gives an identical result
```python
create_tg_link("user", id=self.id)
```
Can be imported from:
```python
from aiogram.utils.link import create_tg_link
```

2022-10-31 23:57 UTC, JrooTJunior requested changes

2022-10-31 23:57 UTC, JrooTJunior commented on aiogram/types/user.py
> +        return create_tg_link("user", self.id)
```suggestion
        return create_tg_link("user", id=self.id)
```

2022-10-31 23:59 UTC, JrooTJunior approved these changes

2022-11-01 16:41 UTC, evgfilim1 approved these changes
Looks good, thanks

2022-11-02 20:40 UTC, merged