update ua docs: contributing.po & flags.po
aiogram/aiogram pull request #1127
Opened 2023-02-13 09:35 UTC by imsLmaooo

# Description

update ua docs: contributing.po & flags.po

## Type of change

- Documentation (typos, code examples or any documentation update)

# How has this been tested?

## Test Configuration
- Operating system: e.g. Ubuntu 20.04.2 LTS
-Python version: e.g. 3.10.1

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have added tests that prove my fix is effective or that my feature works as expected
- [x] New and existing unit tests pass locally with my changes
- [x] My changes generate no new warnings or errors
- [x] My changes are compatible with minimum requirements of the project
- [x] I have made corresponding changes to the documentation

2023-02-15 00:19 UTC, imsLmaooo commented
Who can accidentally come to this pull request, I wanted to download those who are engaged in translating documentation into Ukrainian, for now, take a break, I will translate🙃

2023-02-25 16:08 UTC, JrooTJunior requested changes
Тексти перечитав не повністю, будуть додаткові коментарі.

2023-02-25 16:08 UTC, JrooTJunior commented on docs/locale/uk_UA/LC_MESSAGES/contributing.po
> +"робите це правильно, давайте переформатуємо код автоматично:"
```suggestion
"Зверніть увагу, що цей проект використовує стиль коду Black, тому ви повинні "
"дотримуватися цього стилю, також ви можете переконатись що ви "
"робите це правильно, або виправити стиль коду автоматично:"
```

2023-03-31 10:54 UTC, imsLmaooo commented
можеш з'єднувати, я поки що не буду займатися цим

2025-09-19 20:21 UTC, closed without merging