Added missing FORUM_TOPIC_EDITED value to content_type property
aiogram/aiogram pull request #1160
Opened 2023-04-08 04:20 UTC by MasterGroosha

# Description

Added missing FORUM_TOPIC_EDITED value to content_type property
Fixes #1159

## Type of change

Please delete options that are not relevant.

- [ ] Documentation (typos, code examples or any documentation update)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2023-04-08 14:36 UTC, JrooTJunior requested changes
To fix C416 please merge the latest `dev-3.x` branch.

```
aiogram/filters/magic_data.py:21:41: C416 Unnecessary `dict` comprehension (rewrite using `dict()`)
```

2023-04-08 14:36 UTC, JrooTJunior commented on aiogram/types/message.py
> +            return ContentType.FORUM_TOPIC_EDITED
This line should be covered by tests

2023-04-10 14:18 UTC, MasterGroosha commented
@JrooTJunior I added tests but I cannot run tests properly due to lots of errors and lack of "preparing testing environment" documentation. 
Please test changes yourself or provide more docs.

`make tests` -> `No module named redis`.
Okay, `pip install redis`.
`make tests` -> `ModuleNotFoundError: No module named 'magic_filter'`
Is there one command to install all dependencies for those who hasn't used `hatch` before?

2023-04-16 19:41 UTC, JrooTJunior approved these changes

2023-04-16 19:41 UTC, merged