misc: code consistency and bot instance creation
aiogram/aiogram pull request #1482
Opened 2024-05-08 02:19 UTC by sdmway

# Description

Enhanced the consistency of the codebase by updating the instantiation of the `bot` instance.

Fixes # (issue)

None

Please delete options that are not relevant.

- [x] Documentation (typos, code examples or any documentation update)

# How Has This Been Tested?

Followed steps on: https://docs.aiogram.dev/en/dev-3.x/contributing.html

**Test Configuration**:
* Operating System: MacOS Sonoma 14.4.1
* Python version: 3.11.7

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] New and existing unit tests pass locally with my changes

2024-05-10 03:49 UTC, Olegt0rr commented on examples/echo_bot.py
> +    dp.include_router(echo_router)
We don't need routers in this example, this example should still simple

2024-05-11 17:42 UTC, sdmway commented
@Olegt0rr @JrooTJunior

2024-05-31 17:11 UTC, JrooTJunior requested changes

2024-05-31 17:11 UTC, JrooTJunior commented on CHANGES/1482.misc.rst
> +Enhanced code consistency and readability by refactoring imports, adjusting the base webhook URL, modifying bot instance initialization to utilize DefaultBotProperties, and updating router message ha
```suggestion
Improved code consistency and readability in code examples by refactoring imports, adjusting the base webhook URL, modifying bot instance initialization to utilize DefaultBotProperties, and updating router message handlers.
```

2024-05-31 17:11 UTC, merged