Update callback_data.py
aiogram/aiogram pull request #1493
Opened 2024-05-26 02:05 UTC by m-xim

Allows using a default value in the class which is equal to an empty string ("").

# Description

Currently, the filter does not activate if an empty string ("") is set as the default value in the class. This update corrects that behavior.

## Type of change

Please delete options that are not relevant.

- [ ] Documentation (typos, code examples or any documentation update)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

```
from aiogram import Router, F
from aiogram.filters.callback_data import CallbackData
from aiogram.types import CallbackQuery

class MyCallbackData(CallbackData, prefix="MyCallbackData"):
    input1: str
    input2: str = ""

router = Router()

@router.callback_query(MyCallbackData.filter(F.input1 == "demo"))
async def my_callback(query: CallbackQuery, callback_data: MyCallbackData):

    print("input2 =", callback_data.input2)
```

**Test Configuration**:
* Operating System: Windows 10
* Python version: 3.12.2

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2024-05-27 12:08 UTC, JrooTJunior commented
Please merge branch `dev-3.x` into your branch.

2024-05-30 18:46 UTC, JrooTJunior approved these changes

2024-05-30 18:47 UTC, JrooTJunior requested changes
Please add tests that cover your changes

2024-06-12 14:12 UTC, Olegt0rr requested changes

2024-06-12 14:12 UTC, Olegt0rr commented on aiogram/filters/callback_data.py
> +                    v = field.default if field.default is not PydanticUndefined else None
In this situation, we are already in this state:
```python
v == field.default == "" 
```
You shouldn't set an empty string again. 
Just add another condition under which setting `v = None` will not happen.

2024-06-12 14:18 UTC, Olegt0rr requested changes

2024-06-12 14:18 UTC, Olegt0rr commented on tests/test_filters/test_callback_data.py
> +            foo: Optional[str] = ''
Please, use commands from contribution guide:
https://docs.aiogram.dev/en/dev-3.x/contributing.html#format-the-code-code-style

2024-06-12 14:18 UTC, Olegt0rr commented on tests/test_filters/test_callback_data.py
> +            foo: Optional[str] = ''
```suggestion
            foo: Optional[str] = ""
```

2025-03-10 22:14 UTC, JrooTJunior approved these changes

2025-03-10 22:14 UTC, merged