Fix web_app example
aiogram/aiogram pull request #1546
Opened 2024-07-25 16:11 UTC by bogdan-nikitin

# Description

Fixed URL path in the "Open" button at the "demo/sendMessage" endpoint. 
The button should open the web application, but at the moment it sends a GET request to the current endpoint (which only accepts POST requests).

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

2024-07-26 00:30 UTC, JrooTJunior requested changes

2024-07-26 00:30 UTC, JrooTJunior commented on CHANGES/1538.misc.rst
> -Added method :func:`aiogram.types.message.Message.as_reply_parameters`.
You shouldn't delete this file.

2024-07-26 08:30 UTC, bogdan-nikitin commented on CHANGES/1538.misc.rst
> -Added method :func:`aiogram.types.message.Message.as_reply_parameters`.
Restored

2024-07-27 13:21 UTC, JrooTJunior approved these changes

2024-07-27 13:21 UTC, merged