Increased aiohttp version
aiogram/aiogram pull request #1615
Opened 2024-12-10 23:20 UTC by dolgalevd

# Description

The aiohttp version in the project is outdated and has a number of vulnerabilities.
When installing additional libraries into a project, conflicts arise that cannot be resolved while the aiohttp version is limited to <3.11

Fixes [#1614] (https://github.com/aiogram/aiogram/issues/1614)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

`pytest test`

**Test Configuration**:
* Operating System: MacOs
* Python version: 3.12.4

# Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2024-12-11 06:46 UTC, Olegt0rr approved these changes

2024-12-14 17:31 UTC, JrooTJunior requested changes

2024-12-14 17:31 UTC, JrooTJunior commented on CHANGES/1615.misc.rst
> +Increased aiohttp upper limit
```suggestion
Increased max :code:`aiohttp` version support from “<3.11” to “<3.12”
```

2024-12-14 17:32 UTC, JrooTJunior approved these changes

2024-12-14 17:32 UTC, merged