feat(InputFile): adding Pathlib to supporting types for files
aiogram/aiogram pull request #442
Opened 2020-10-13 11:56 UTC by amalkhamidov

# Description

❤️ This change allows the Pathlib library to be used as a path reference for InputFile!

2020-11-05 13:23 UTC, evgfilim1 reviewed
LGTM, thanks

2020-11-07 21:21 UTC, JrooTJunior requested changes

2020-11-07 21:21 UTC, JrooTJunior commented on aiogram/types/input_file.py
> +
Filename should be resolved in the same way as it with string `path_or_bytesio`

```suggestion
            if filename is None:
                filename = path_or_bytesio.name
```

2020-11-07 21:22 UTC, JrooTJunior approved these changes

2020-11-07 21:22 UTC, merged