enh: Text filter contains_any parameter added
aiogram/aiogram pull request #626
Opened 2021-07-08 17:11 UTC by hoodwinker

# Description

Text filter extended with "contains_any" parameter. 
"contains" works for all values, "contains_any" for any of.

## New feature

- [ ] New feature (non-breaking change which adds functionality)

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-07-08 17:26 UTC, evgfilim1 commented on aiogram/dispatcher/filters/builtin.py
> -
Why have you deleted this?

2021-07-08 18:10 UTC, hoodwinker commented on aiogram/dispatcher/filters/builtin.py
> -
my fault, wrong source

2021-07-09 04:36 UTC, Olegt0rr requested changes
You should also add an [example](https://github.com/aiogram/aiogram/blob/dev-2.x/examples/text_filter_example.py)

2023-08-04 18:34 UTC, JrooTJunior commented
v2 will no more be supported.

2023-08-04 18:34 UTC, closed without merging