aioredis v2 support
aiogram/aiogram pull request #649
Opened 2021-08-01 09:02 UTC by Olegt0rr

# Description
We should add non-compatibility-breakable support for aioredis v2

Fixes #648

## Type of change

Please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-08-01 09:15 UTC, evgfilim1 reviewed
IMO it breaks backwards compatibility anyway. `RedisStorage2.redis()` is public, so some code might rely on this method and its return type.
Also is it safe to rely on `importlib.metadata.version`?

2021-08-01 13:35 UTC, Olegt0rr commented
> IMO it breaks backwards compatibility anyway. `RedisStorage2.redis()` is public, so some code might rely on this method and its return type.
> Also is it safe to rely on `importlib.metadata.version()`?

I've proxied methods from Redis, so now public `.redis()` method may be used as an original Redis

2021-08-02 20:55 UTC, evgfilim1 requested changes
There's a bug. Choose one of two possible fixes

2021-08-02 20:55 UTC, evgfilim1 commented on aiogram/contrib/fsm_storage/redis.py
> +            elif redis_version == 2:
You're comparing `str` with `int`
```suggestion
            if redis_version == "1":
                self._redis = AioRedisAdapterV1(**connection_data)
            elif redis_version == "2":
```

2021-08-02 20:55 UTC, evgfilim1 commented on aiogram/contrib/fsm_storage/redis.py
> +            redis_version = aioredis.__version__.split(".")[0]
See above
```suggestion
            redis_version = int(aioredis.__version__.split(".")[0])
```

2021-08-05 13:24 UTC, evgfilim1 approved these changes

2021-08-05 19:34 UTC, JrooTJunior approved these changes

2021-08-05 19:34 UTC, merged

2021-08-11 11:49 UTC, paul1319 commented
There is a bug `AttributeError: module 'aioredis' has no attribute 'RedisConnection'`

2021-08-30 14:06 UTC, Olegt0rr commented on aiogram/contrib/fsm_storage/redis.py
> +        async with self._connection_lock:
Fixed in #676