from .message import Message for line 36
aiogram/aiogram pull request #684
Opened 2021-09-07 05:25 UTC by cclauss

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Documentation (typos, code examples or any documentation update)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Operating System: 
* Python version: 

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-09-07 17:56 UTC, Olegt0rr commented
1. No description
2. It's a bad practice for type cross importing. Sometimes it may produce a cycled import. String typing is better solution

2021-09-07 18:35 UTC, Olegt0rr requested changes

2021-09-07 18:35 UTC, Olegt0rr commented on aiogram/types/chat.py
> +from .message import Message
It's a bad practice for type cross importing. Sometimes it may produce a cycled import. String typing is better solution

2021-09-09 21:09 UTC, JrooTJunior commented
This change produces more circular imports, that's bad practice.
I will close this PR.

2021-09-09 21:09 UTC, closed without merging