I suggest adding a new builtin filter
aiogram/aiogram pull request #711
Opened 2021-09-28 22:09 UTC by LDmitriy7

# Description

Fixes #566

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Tested all cases from issue #566

**Test Configuration**:
* Operating System: Windows 10
* Python version: 3.9

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2021-09-29 10:54 UTC, Olegt0rr requested changes

2021-09-29 10:54 UTC, Olegt0rr commented on aiogram/dispatcher/filters/builtin.py
> +        self.storage_data = storage_data
Storage type hint set in arguments, but dispatcher type hint set inside the function.
Please make it similar way.

2021-09-29 10:54 UTC, Olegt0rr commented on aiogram/dispatcher/filters/builtin.py
> +    """
Please, add examples to:
1. `examples` folder
2. `StorageDataFilter` docstrings

Also don't forget to add description of asterisk behaviour

2021-12-06 22:57 UTC, JrooTJunior commented
@LDmitriy7, FYI

Any news about requested changes?

2022-03-21 16:48 UTC, evgfilim1 commented
Closing as inactive. Feel free to comment here if you need or push your changes.

2022-03-21 16:48 UTC, closed without merging