Implemented mongodb storage
aiogram/aiogram pull request #781
Opened 2021-12-15 19:11 UTC by asimaranov

Implemented the mongodb storage. Added some tests like in redis storage. Added motor dependency

2021-12-16 15:20 UTC, uburuntu requested changes
Thanks for the PR! Overall lgtm.

I'm not familiar with MongoDB, so hope someone will check its usage.

2021-12-16 15:20 UTC, uburuntu commented on pyproject.toml
> +motor = "^2.5.1"
Make this optional, please, as `aioredis` from previous lines

2021-12-16 15:20 UTC, uburuntu commented on tests/conftest.py
> +    storage = MongoStorage.from_url(redis_server)
And change the variable name, it's confusing currently :)

2021-12-16 15:58 UTC, Tishka17 commented on aiogram/dispatcher/fsm/storage/mongo.py
> +    raise e
Just `raise`

2021-12-16 16:16 UTC, WhiteMemory99 commented on pyproject.toml
> +motor = { version = "^2.5.1", optional = true }
It would be nice to add this dependency to the extras section below.

2022-01-01 11:04 UTC, evgfilim1 commented
Hello, @asimaranov, and thanks for contributing! If you've finished working on this feature, please reformat your code with `make reformat` so the tests can pass.

2022-01-01 12:35 UTC, asimaranov commented
Why can it throw "E   ModuleNotFoundError: No module named 'motor'"?

2022-01-01 12:43 UTC, evgfilim1 commented
> Why can it throw "E ModuleNotFoundError: No module named 'motor'"?

@asimaranov, because it's not installed during testing. Look how Redis is tested in [`tests/`](https://github.com/aiogram/aiogram/tree/dev-3.x/tests) directory and [`.github/workflows/tests.yml`](https://github.com/aiogram/aiogram/blob/dev-3.x/.github/workflows/tests.yml) and set it up similarly.

2022-01-01 12:47 UTC, evgfilim1 requested changes

2022-01-01 12:47 UTC, evgfilim1 commented on poetry.lock
> +optional = false
Please update lockfile also, this should become `true`
https://github.com/aiogram/aiogram/blob/6e39f9fada99906567d889c9618f65bc2f089c44/poetry.lock#L47

2024-01-28 18:37 UTC, KobetsDev commented
can you tell me why PR was abandoned?

2024-01-28 23:58 UTC, JrooTJunior commented
> can you tell me why PR was abandoned?

The author of this PR is inactive and has not responded for a long time, but the code from this PR can be reused to implement Mongo storage.

2024-02-15 19:54 UTC, closed without merging