Adding functions ban, unban in users.py
aiogram/aiogram pull request #849
Opened 2022-02-25 19:12 UTC by ProgramUser5353

2022-02-25 19:49 UTC, Olegt0rr commented
Please STOP.
I'm beggin

2022-02-26 03:41 UTC, evgfilim1 requested changes
Also, please fill in pull request template, don't ignore it!

2022-02-26 03:41 UTC, evgfilim1 commented on aiogram/types/user.py
> +        return await self.bot.ban_chat_member(self.chat.id, self.id, until_date=until_date,
`AttributeError: 'User' object has no attribute 'chat'`

2022-02-26 03:41 UTC, evgfilim1 commented on aiogram/types/user.py
> +        return await self.bot.unban_chat_member(self.chat.id,
`AttributeError: 'User' object has no attribute 'chat'`

2022-02-26 03:49 UTC, evgfilim1 commented
You cannot implement these methods on User object, as ban and unban requires chat_id. It even doesn't really fit here semantically. Ban and unban are more appropriate for Chat object, but they already exist there. Closing as won't fix.

2022-02-26 03:49 UTC, closed without merging

2022-02-26 07:16 UTC, ProgramUser5353 commented
> You cannot simply implement these methods on User object, as ban and unban requires chat_id. It even doesn't really fit here semantically. Ban and unban are more appropriate for Chat object, but they already exist there. Closing as won't fix.

but it is possible to get value of ID from users somehow?

2022-02-26 07:30 UTC, evgfilim1 commented
> but it is possible to get value of ID from users somehow?

User ID is known, but in order to ban the user, you have to provide a chat_id in which you want to ban him.