fix #349
aiogram/aiogram pull request #880
Opened 2022-04-09 15:20 UTC by arynyklas

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Operating System: 
* Python version: 

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-04-11 00:42 UTC, JrooTJunior requested changes

2022-04-11 00:42 UTC, JrooTJunior commented on aiogram/types/fields.py
> +        return (value - datetime.datetime(1970, 1, 1)).total_seconds()
round returns int, total_seconds() returns float, so this methods in not equivalent
Also this dirty-hack is needed only on Windows, so please make an platform-specific function and use it here.

For example at module root (pseudo-code):
```python
if sys.platform == "win32":
    def _serialize_datetime(value):
        return round(...total_seconds())
else:
    def _serialize_datetime(value):
        return round(...timestamp())
```

2022-04-24 01:01 UTC, JrooTJunior approved these changes

2022-04-24 01:01 UTC, merged

2022-05-11 19:49 UTC, fifthsound commented
@arynyklas  For win7 have to change also deserialize:

`    
if sys.platform == "win32":
      def serialize(self, value: datetime.datetime):
          return round((value - datetime.datetime(1970, 1, 1)).total_seconds())
      **def deserialize(self, value, parent=None):
          return value**
  else:
      def serialize(self, value: datetime.datetime):
          return round(value.timestamp())
      def deserialize(self, value, parent=None):
          return datetime.datetime.fromtimestamp(value)
`

2022-05-12 01:21 UTC, arynyklas commented
> @arynyklas For win7 have to change also deserialize:
> 
> ```
> if sys.platform == "win32":
>     def serialize(self, value: datetime.datetime):
>         return round((value - datetime.datetime(1970, 1, 1)).total_seconds())
>     def deserialize(self, value, parent=None):
>         return value
> else:
>     def serialize(self, value: datetime.datetime):
>         return round(value.timestamp())
>     def deserialize(self, value, parent=None):
>         return datetime.datetime.fromtimestamp(value)
> ```

deserialize need to return datetime.datetime

2022-05-13 19:19 UTC, fifthsound commented
> @arynyklas For win7 have to change also deserialize:
> deserialize need to return datetime.datetime

Yes, I mean that the same error on windows also exist for deserialization.

Get this error: 
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\
aiogram\dispatcher\dispatcher.py", line 385, in start_polling
    allowed_updates=allowed_updates
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\
aiogram\bot\bot.py", line 111, in get_updates
    return [types.Update(**update) for update in result]
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\
aiogram\bot\bot.py", line 111, in <listcomp>
    return [types.Update(**update) for update in result]
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\
aiogram\types\base.py", line 95, in __init__
    self.props[key].set_value(self, value, parent=self)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\
aiogram\types\fields.py", line 58, in set_value
    value = self.deserialize(value, parent)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\
aiogram\types\fields.py", line 116, in deserialize
    return self.base_object.to_object(conf={'parent': parent}, data=value)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\
aiogram\types\base.py", line 153, in to_object
    return cls(conf=conf, **data)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\
aiogram\types\base.py", line 95, in __init__
    self.props[key].set_value(self, value, parent=self)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\
aiogram\types\fields.py", line 58, in set_value
    value = self.deserialize(value, parent)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\
aiogram\types\fields.py", line 116, in deserialize
    return self.base_object.to_object(conf={'parent': parent}, data=value)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\
aiogram\types\chat_member.py", line 97, in to_object
    return cls.resolve(conf=conf, **data)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\
aiogram\types\chat_member.py", line 88, in resolve
    return class_(**kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\
aiogram\types\base.py", line 95, in __init__
    self.props[key].set_value(self, value, parent=self)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\
aiogram\types\fields.py", line 58, in set_value
    value = self.deserialize(value, parent)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\
aiogram\types\fields.py", line 176, in deserialize
    return datetime.datetime.fromtimestamp(value)
OSError: [Errno 22] Invalid argument