Added an example of a bot based on a class and asyncio
aiogram/aiogram pull request #893
Opened 2022-04-22 06:48 UTC by vortex14

2022-04-24 01:00 UTC, JrooTJunior commented
Please explain the motivation for adding this example?

2022-05-09 16:43 UTC, vortex14 commented
> Please explain the motivation for adding this example

1. It is not always convenient to use only decorators to describe the bot
2. It is not always necessary to use the native way to get the bot update through the executor.start_polling() method
3. Sometimes the bot needs to be integrated into the API at the same time, for example FastAPI and without using the event loop the executor will block the execution
3. There were no simple examples for class-based code layout.

2022-05-12 21:59 UTC, Olegt0rr commented
Use polling from Dispatcher. It's nonblocking.
Anyway, class-based bot is not a solution

2022-05-12 22:03 UTC, evgfilim1 requested changes
I don't understand why you spawn tasks…

2022-05-12 22:03 UTC, evgfilim1 commented on examples/echo_class_based_bot_asyncio.py
> +        asyncio.create_task(self.dp.start_polling())
```suggestion
        await self.dp.start_polling()
```

2022-05-12 22:03 UTC, evgfilim1 commented on examples/echo_class_based_bot_asyncio.py
> +    loop.run_forever()
```suggestion
    asyncio.run(bot.run())
```

2022-05-13 05:49 UTC, vortex14 commented
> 



> Use polling from Dispatcher. It's nonblocking. Anyway, class-based bot is not a solution

That is, you design all bots through decorators in one file? Are you using classes to build complex applications?

2022-05-13 06:45 UTC, vortex14 commented
> I don't understand why you spawn tasks…

Ok, You are right for this case, but I uploaded a new example on FastAPI based and how you apply this polling without create task ??

2022-05-13 09:13 UTC, evgfilim1 commented
> > Use polling from Dispatcher. It's nonblocking. Anyway, class-based bot is not a solution
> 
> That is, you design all bots through decorators in one file? Are you using classes to build complex applications?

Nothing prevents you to use `dp.register_foo_handler(...)` and split your bot into several files. See #522 also.

2022-05-13 10:44 UTC, vortex14 commented
> Nothing prevents you to use

ok, but this is different way for create application, I and added a few examples for this, which nothing in example directories. 
Do you think this is a few examples are useless (FastApi, class Based, asyncio)?

2022-05-13 11:22 UTC, evgfilim1 commented
> Do you think this is a few examples are useless (FastApi, class Based, asyncio)?

I think class-based one is useless (why do you even need this? how can it help?) and FastAPI one is confusing (what is `fastapi_utils` and why do you use it when you can achieve the same without installing extra package?). 

I'd also like to hear an opinion from @JrooTJunior and @Olegt0rr.

2022-05-13 12:32 UTC, vortex14 commented
> > Do you think this is a few examples are useless (FastApi, class Based, asyncio)?
> 
> I think class-based one is useless (why do you even need this? how can it help?) and FastAPI one is confusing (what is `fastapi_utils` and why do you use it when you can achieve the same without installing extra package?).
> 
> I'd also like to hear an opinion from @JrooTJunior and @Olegt0rr.


1. Skeleton class based architecture without decorators 
2. Example using asyncio library 
3. Example integration fastapi with bot

All this all copy/past without additional research (stackoverflow and etc resource)

Main goal save to time and give a finished skeleton for differents design.

I think the more examples there are the better. 

If persoly these example useless your, they may be usefull for others )
Do you use FastAPI? 

fastapi_utils usefull library for decomposing subrouting. 
I can add and base example fastapi, but in real project better use cbv for separates files and routing.

2022-05-13 13:03 UTC, vortex14 commented
> > > Use polling from Dispatcher. It's nonblocking. Anyway, class-based bot is not a solution
> > 
> > 
> > That is, you design all bots through decorators in one file? Are you using classes to build complex applications?
> 
> Nothing prevents you to use `dp.register_foo_handler(...)` and split your bot into several files. See #522 also.

Why is the example from the discussion not presented as a separate example in the examples folder?

2022-05-13 14:14 UTC, vortex14 commented
> I agree that #522 should be added to the docs.
> 
> But I'm against wraping an already class-based Bot with another class. It's redundant. This is an antipattern.
> 
> All explained motivation may be solved other way

ok, write please example how organize code for commands and subcommands bot in different space(file, class or etc)?
1. Command on top level
2. Command on sub level 
3. Command on sub/sub level
main command /user -> /add -> /asign role

please micro example for best practice pattern.

2022-05-13 20:00 UTC, evgfilim1 commented
> please micro example for best practice pattern.

I think this and further future questions not related to this pull request should be moved into discussions

2022-05-13 20:10 UTC, evgfilim1 commented on examples/echo_fastapi_based_bot.py
> +        asyncio.create_task(self.dp.start_polling())
FastAPI with polling :/
IMO, this doesn't make any sense since you already have a web server running.

2022-05-13 20:10 UTC, evgfilim1 commented on examples/echo_fastapi_cbv_based_bot.py
> +        asyncio.create_task(self.dp.start_polling())
Same here

2022-05-13 23:53 UTC, vortex14 commented
> > please micro example for best practice pattern.
> 
> I think this and future questions not related to this pull request should be moved into discussions

https://github.com/aiogram/aiogram/discussions/910

2023-08-04 18:34 UTC, JrooTJunior commented
v2 will no more be supported.

2023-08-04 18:34 UTC, closed without merging