Allow to use `int` and `datetime.timedelta` in `RedisStorage.state_ttl` and `RedisStorage.data_ttl`
aiogram/aiogram pull request #922
Opened 2022-06-12 16:38 UTC by andrew000

# Description

Allow to use `int` and `datetime.timedelta` in `RedisStorage.state_ttl` and `RedisStorage.data_ttl`

In `aioredis` source code it is allowed to use `int` and `datetime.timedelta` to set expiration time for key, ([Source](https://github.com/aio-libs/aioredis-py/blob/19be499015a8cf32580e937cbfd711fd48489eca/aioredis/client.py#L2037), [ExpiryT](https://github.com/aio-libs/aioredis-py/blob/19be499015a8cf32580e937cbfd711fd48489eca/aioredis/client.py#L55))

## Type of change

- [ ] This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2022-06-13 16:40 UTC, Olegt0rr approved these changes

2022-06-13 16:48 UTC, Olegt0rr requested changes

2022-06-13 16:48 UTC, Olegt0rr commented on aiogram/dispatcher/fsm/storage/redis.py
> +from redis.asyncio.client import ExpiryT, Redis
Try this
```suggestion
from redis.asyncio.client import Redis
from redis.typing import ExpiryT
```

2022-06-15 17:49 UTC, Olegt0rr approved these changes

2022-06-15 18:53 UTC, JrooTJunior approved these changes

2022-06-16 18:43 UTC, merged