Refactor: changed the `resolve_event_context` method to human-readable
aiogram/aiogram pull request #986
Opened 2022-08-23 09:26 UTC by NiKuma0

Refactor: changed the `resolve_event_context` method of `UserContextMiddleware` class to human-readable

2022-08-23 09:31 UTC, Olegt0rr commented
Current solution is better than suggested.

2022-08-23 09:34 UTC, Olegt0rr requested changes

2022-08-23 09:34 UTC, Olegt0rr commented on aiogram/dispatcher/middlewares/user_context.py
> +        return getattr(parametr, 'chat', None), getattr(parametr, 'from_user', None)
it's wrong for `poll_answer`

2022-08-23 10:16 UTC, gabbhack requested changes

2022-08-23 10:16 UTC, gabbhack commented on aiogram/dispatcher/middlewares/user_context.py
> +            if event.inlinee_query.message:
typo

2022-08-23 15:07 UTC, NiKuma0 commented
> Current solution is better than suggested.

Why? 
Okay, I understand that maybe my code will run slower than before (by quite a bit). But it's really the most human readable.

2022-08-24 09:56 UTC, JrooTJunior commented
> Okay, I understand that maybe my code will run slower than before (by quite a bit). But it's really the most human readable.

We have already tested such a solution 10 months ago. This solution is slower than current by 4 times and this is due to the use of a cycle with the selection of redundant parameters instead of direct access.

The processing speed might be critical for high-loaded bots

As The Zen of Python says - Explicit is better than implicit.

About readability, i don't thing the for-loop with `gettattr` is more readability instead of plain if-conditions.

---

Also your code doesn't follows project code-style (black)

2022-08-24 09:56 UTC, closed without merging